TOPICS = [
    {'name': 'Arrays', 'slug': 'arrays', 'icon': '📊', 'description': 'Linear data structure for storing elements of the same type.', 'display_order': 1},
    {'name': 'Strings', 'slug': 'strings', 'icon': '🔤', 'description': 'Character sequences and text manipulation.', 'display_order': 2},
    {'name': 'Linked Lists', 'slug': 'linked-lists', 'icon': '🔗', 'description': 'Linear collections of data elements, where linear order is not given by physical placement in memory.', 'display_order': 3},
    {'name': 'Stack', 'slug': 'stack', 'icon': '📚', 'description': 'LIFO data structures.', 'display_order': 4},
    {'name': 'Queue', 'slug': 'queue', 'icon': '🚶', 'description': 'FIFO data structures.', 'display_order': 5},
    {'name': 'Hashing', 'slug': 'hashing', 'icon': '#️⃣', 'description': 'Mapping keys to values for fast access.', 'display_order': 6},
    {'name': 'Recursion', 'slug': 'recursion', 'icon': '🔄', 'description': 'Solving problems where a function calls itself.', 'display_order': 7},
    {'name': 'Trees', 'slug': 'trees', 'icon': '🌳', 'description': 'Hierarchical structures.', 'display_order': 8},
    {'name': 'Binary Search Tree', 'slug': 'bst', 'icon': '🌲', 'description': 'Ordered binary trees.', 'display_order': 9},
    {'name': 'Heaps', 'slug': 'heaps', 'icon': '⛰️', 'description': 'Priority queues and heap properties.', 'display_order': 10},
    {'name': 'Graphs', 'slug': 'graphs', 'icon': '🕸️', 'description': 'Networks of vertices and edges.', 'display_order': 11},
    {'name': 'Dynamic Programming', 'slug': 'dynamic-programming', 'icon': '🧩', 'description': 'Solving complex problems by breaking them down into simpler subproblems.', 'display_order': 12},
    {'name': 'Greedy', 'slug': 'greedy', 'icon': '🎯', 'description': 'Making locally optimal choices at each step.', 'display_order': 13},
    {'name': 'Backtracking', 'slug': 'backtracking', 'icon': '↩️', 'description': 'Finding all (or some) solutions incrementally.', 'display_order': 14},
    {'name': 'Sorting', 'slug': 'sorting', 'icon': '📶', 'description': 'Ordering elements.', 'display_order': 15},
    {'name': 'Two Pointers', 'slug': 'two-pointers', 'icon': '👉👈', 'description': 'Technique using two indices to traverse a data structure.', 'display_order': 16},
    {'name': 'Sliding Window', 'slug': 'sliding-window', 'icon': '🪟', 'description': 'Maintaining a subset of elements within a larger set.', 'display_order': 17},
    {'name': 'Binary Search', 'slug': 'binary-search', 'icon': '🔍', 'description': 'Efficiently finding an item from a sorted list of items.', 'display_order': 18},
]
